apiVersion: apps/v1
kind: Deployment
metadata:
  name: opscenter
  labels:
    app: opscenter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opscenter
  template:
    metadata:
      labels:
        app: opscenter
    spec:
      containers:
        - name: opscenter
          image: opscenter:nightly
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_PASSWORD
              value: "mysql123"
            - name: MYSQL_ADDRESS
              value: "192.168.0.103"
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_DATABASE
              value: "kubehostwarden"
            - name: HOST_COLLECTOR_IMAGE
              value: "host:nightly"
            - name: INFLUXDB_BUCKET
              value: "kubehostwarden"
            - name: INFLUXDB_ORG
              value: "myorg"
            - name: INFLUXDB_URL
              value: "http://192.168.0.103:8086"
            - name: INFLUXDB_TOKEN
              value: "aBtrkWRZwa8t_JDtHlEvX6r83DuVpxQhsy6KyxtA9gKiAWgXK42zNP9s9HTj3ty0pV4JeDndOKH5fsoKP6Kktg=="
