FROM golang:1.21 as builder

WORKDIR /app
COPY . .

RUN go mod download

RUN CGO_ENABLED=0 GOOS=linux go build -a -o opscenter cmd/opscenter/opscenter.go

FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=builder /app/opscenter .
COPY --from=builder /app/.env .
CMD ["./opscenter"]