apiVersion: v1
kind: Service
metadata:
  name: opscenter-service
spec:
  type: LoadBalancer # 或者使用 LoadBalancer，如果你的环境支持
  selector:
    app: opscenter
  ports:
    - port: 8080
      targetPort: 8080
